### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by suhlig** [aequitas/concourse-http-resource#5]
I just wanted to say THANK YOU for this resource! I need to track Vagrant releases, and they do not publish proper GitHub releases. Once I found your resource, it was as simple as this:

```yaml
- name: Vagrant Release
  type: http
  source:
    index: https://releases.hashicorp.com/vagrant/
    regex: 'href="/vagrant/(?P<version>[0-9\.]+)'
    uri: 'https://releases.hashicorp.com/vagrant/{version}/vagrant_{version}_SHA256SUMS'
```

So, thank you again for making my Concourse life easier!

Best regards

Steffen
